---
- name: Install dependencies
  hosts: raspi
  become: yes ## Make sure we elevate permissions to root
  tasks:
   - name: Install vlc
     ansible.builtin.apt:
       pkg:
         - vlc
         - v4l-utils
       update_cache: yes
