---
- name: Install dependencies
  hosts: raspi
  become: yes ## Make sure we elevate permissions to root
  tasks:
   - name: Install vlc
     ansible.builtin.apt:
       pkg:
         - vlc
         - v4l-utils
       update_cache: yes

- name: Deploy image capturer
  hosts: raspi
  tasks:
    - name: Create Workspace directory
      file:
        path: ~/image-capturer
        state: directory
        mode: '0775'
    - name: Copy over source
      copy:
        src: ../image-capturer/image_capturer
        dest: ~/image-capturer/

    - name: Copy over pyproject.toml
      copy:
        src: ../image-capturer/pyproject.toml
        dest: ~/image-capturer/pyproject.toml

    - name: Copy over requirements
      copy:
        src: ../image-capturer/requirements.txt
        dest: ~/image-capturer/requirements.txt

    - name: Install requirements
      pip:
        requirements: ~/image-capturer/requirements.txt
        extra_args: --user

    - name: Set env for load balancer
      cron:
        name: "BACKEND_HOST"
        value: "{{ lookup('ansible.builtin.env', 'BACKEND_HOST') }}"
        user: "growlab"
        env: true

    - name: Create cron job for taking images
      cron:
        name: "MakeImage"
        minute: "*/15"
        weekday: "*"
        hour: "*"
        user: "growlab"
        job: "python3 ~/image-capturer/image_capturer/main.py"
